myapps/form/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login 

from . import views

app_name = 'form'

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^signup_small/$',views.signup_small,name='signup_small'),
	url(r'^login/$', auth_views.login,{'template_name': 'form/signin.html','extra_context':{'page':'login'}}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'form:index'}, name='logout'),
	url(r'^work_space/$',views.work_space,name='work_space'),
	url(r'^profile/$',views.update_profile,name='profile'),
	
	url(r'^oauth/', include('social_django.urls', namespace='social')),  # <--
	url(r'^admin/', admin.site.urls),



	# ajax calls
	url(r'^check_get_user/$', views.check_get_user, name='check_get_user'),
	url(r'^profile/form/check_get_user/$', views.check_get_user, name='check_get_user'),
	
	
	url(r'^multiple_form/$',views.example_multi_form,name='multiple_form'),
	url(r'^success/$',views.success,name='success'),
	url(r'^example_form/$',views.example_form,name='example_form'),

]

myapps/myapps/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^form/',include('form.urls')),
	url(r'^social/',include('social_django.urls')),

]

myapps/form/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=30, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

myapps/form/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, MultiField, HTML, Div, Submit, Button
from crispy_forms.bootstrap import FormActions,InlineField
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile



class SignUpSmall(UserCreationForm):
	username = forms.CharField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Username','name':'user'}),
	)
	email = forms.EmailField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Email','name':'email'}),
	)
	password1 = forms.CharField(
		label='',
		max_length=100,
		widget=forms.PasswordInput(attrs={'placeholder': 'Password','name':'password1'}),
	)
	password2 = forms.CharField(
		label='',
		max_length=100,
		widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password','name':'password2'}),
	)
	
	# terms_cond = forms.BooleanField(
	# 	label = 'I agree to terms and conditions',
	# )
	


	def __init__(self,*args,**kwargs):
		super(SignUpSmall,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'POST'
		self.helper.form_class = 'form-horizontal'
		self.helper.form_id = 'loginForm'
		#self.helper.attrs = {'data-toggle':'validator','role':'form'}
		

		self.helper.label_class='col-lg-2'
		self.helper.field_class='col-lg-8 col-md-offset-2'
		self.helper.layout = Layout(
			Fieldset(		
				'',
				'username',
				'email',
				'password1',
				'password2',
				'terms_cond',
			),
			FormActions(
 	   			Submit('save', 'Register'),
    			Button('cancel', 'Already have an account?')
			),
		)
		
		class Meta:
			model = User
	    	fields = ('username', 'email', 'password1','password2')
		
	def save(self, commit=True):
		user = super(SignUpSmall, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user
			

		

class ProfileForm(forms.ModelForm):
    
		
    contact = forms.CharField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Contact','name':'contact'}),
		required=False,
	)
	
    birth_date = forms.DateField(
    	label='',
    	widget=forms.DateTimeInput(attrs={'placeholder':'Date of Birth','name':'birth_date'}),
    	required=False,
    )
    
    location = forms.CharField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Address','name':'location'}),
		required=False,
	)
	
    class Meta:
		model = Profile
		fields = ('contact', 'location', 'birth_date')	
		
    def __init__(self,*args,**kwargs):
		super(ProfileForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'POST'
		self.helper.form_class = 'form-horizontal'
		
	

		
	
		
		
class SignIn(forms.Form):
	username = forms.CharField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Username','name':'user'}),
	)
	password = forms.CharField(
		label='',
		max_length=100,
		widget=forms.TextInput(attrs={'placeholder': 'Password','name':'password'}),
	)
		
	def __init__(self,*args,**kwargs):
		super(SignIn,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'POST'
		self.helper.form_class = 'form-horizontal'
		self.helper.form_id = 'loginForm'
		self.helper.label_class='col-lg-2'
		self.helper.field_class='col-lg-8 col-md-offset-2'
		self.helper.layout = Layout(
			Fieldset(		
				'',
				'username',
				'password',
			),
			FormActions(
 	   			Submit('save', 'Sign in'),
    			Button('cancel', 'Dont have an account? Sign Up')
			),
		)
		
		
		
		
		

class ExampleForm(forms.Form):
	like_website = forms.TypedChoiceField(
		label = "Do you like this website?",
		choices = ((1,"Yes"),(0,"No")),
		coerce = lambda x: bool(int(x)),
		widget = forms.RadioSelect,
		initial = '1',
		required = True,
	)

	favorite_food = forms.CharField(
		label = "What is your favorite food?",
		max_length = 80,
		required = True,
	)
	
	favorite_color = forms.CharField(
		label = "What is your favorite color?",
		max_length = 80,
		required = True,
	)

	favorite_number = forms.CharField(
		label = "What is your favorite number?",
		max_length = 80,
		required = True,
	)

	notes = forms.CharField(
		label = "Additional notes or feedback",
		required = True,
	)
	

	def __init__(self,*args,**kwargs):
		super(ExampleForm,self).__init__(*args,**kwargs)
		self.helper=FormHelper()
		self.helper.form_id = 'id-exampleForm'
		#self.helper.form_class='blueForms'
		self.helper.label_class= 'col-lg-2'
		self.helper.field_class= 'col-lg-8'
		#self.helper.form_method='POST'
		#self.helper.form_action='submit_survey'
		#self.helper.form_tag = False	
		
		#self.helper.add_input(Submit('submit','Submit'))
		self.helper.layout = Layout(
    			Fieldset(
        			'Tell us your favorite stuff',
            			'like_website',
            			'favorite_number',
				'favorite_color',
        			'favorite_food',
        			'notes'
    			)
		)
		

	


class ButtonForm(forms.Form):
	

	def __init__(self,*args,**kwargs):
		super(ButtonForm,self).__init__(*args,**kwargs)
		self.helper = FormHelper()
		self.helper.form_class = 'form-horizontal'
		self.helper.form_id = 'id-buttonform'
		self.helper.label_class='col-lg-2'
		self.helper.field_class='col-lg-8 col-md-offset-2'
		self.helper.layout = Layout(
			FormActions(
				Submit('{% url "signup_small" %}','Register'),
				Button('login','Already have an account?'),
			),
		)

myapps/form/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


from django.db import transaction
from .forms import SignUpSmall,ExampleForm,ButtonForm,SignIn, ProfileForm


from django.contrib.auth.decorators import login_required

from django.http import JsonResponse



def index(request):
	return render(request,'form/welcome.html',{'title':'Welcome','page':'welcome'})




def signup_small(request):
	if request.method == 'POST':
		form = 	SignUpSmall(request.POST)
		if form.is_valid():
			try:
				form.save()
				username = form.cleaned_data.get('username')
				raw_password = form.cleaned_data.get('password1')
				print form.cleaned_data.get('username')
				print form.cleaned_data.get('email')
				user = authenticate(username=username, password=raw_password)
				if user is not None:
					login(request, user)
					return redirect('form:work_space')
				else:
					raise Exception("User is none")
			except Exception as e:
				print e.message
			else:
				return redirect('form:success')
	else:
		form = SignUpSmall()

	return render(request,'form/signup_small.html',{'form':form})






@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
    	print request.user
    	user_form = SignUpSmall(request.POST, instance=request.user)
    	profile_form = ProfileForm(request.POST, instance=request.user.profile)
    	if user_form.is_valid():
        	user_form.save()
        	messages.success(request, _('Your profile was successfully updated!'))
        else:
        	user_form = SignUpSmall(instance=request.user)
        	messages.error(request, _('Please correct the error below.'))
    	if profile_form.is_valid():
			profile_form.save()
			messages.success(request, _('Your profile was successfully updated!'))
    	else:
    		profile_form = ProfileForm(instance=request.user.profile)
        	messages.error(request, _('Please correct the error below.'))
    else:
        user_form = SignUpSmall(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    
    return render(request, 'form/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })






def success(request):
	return HttpResponse("Registered Successfully")





def signin_verify(request):
	print 'in 1'
	if request.method == 'POST':
		print 'in 2'
		form = 	SignIn(request.POST)
		if form.is_valid():
			print 'in 3'
			try:
				print 'in 4'
				username = request.POST['username']
				raw_password = request.POST['password']
				user = authenticate(username=username, password=raw_password)
				if user is not None:
					print 'in 5'
					if user.is_active:
						
						login(request, user)
						return redirect('form:work_space')
					else:
						print 'already logged in'
				else:
					print 'in 6'
					raise Exception("No such user")
			except:
				return HttpResponse('database error')
			else:
				return redirect('form:work_space')
	else:
		form = SignIn()
	return render(request,'form/signin.html',{'form':form})




def signout(request):
	logout(request)
	redirect('form:index')




def work_space(request):
	return render(request,'form/work_space.html',{'title':'Work Space','page':'work_space'})







def example_form(request):
	if request.method == 'POST':
		form = ExampleForm(request.POST)
	else:
		form = ExampleForm()
	return render(request,'form/signup_small.html',{'form':form,'helper':form.helper})
	
	
	

			

def example_multi_form(request):
	if request.method == 'POST':
		small_form = SignUpSmall(request.POST)
		example_form = ExampleForm(request.POST)
		button_form  = ButtonForm(request.POST)
	else:
		small_form = SignUpSmall()
		example_form = ExampleForm()
		button_form = ButtonForm()
	small_form.helper.form_tag = False
	example_form.helper.form_tag = False
	return render(request,'form/multiple_form.html',{'small_form':small_form,'example_form':example_form,'button_form':button_form})
	
	
	
# helper methods for ajax calls

def check_get_user(request):
    username = request.GET.get('username', None)
    print username
    
    valid = False
    email = 'Email'
    contact = 'Contact'
    address = 'Address'
    birth_date = 'Date of Birth'
    password = ''
    
    if User.objects.filter(username__iexact=username).exists():
    	valid = True
    	user = User.objects.get(username=username)
    	email = user.email
    	if user.profile.contact is not '':
    		contact = user.profile.contact
    	if user.profile.location is not '':
    		address = user.profile.location
    	if user.profile.birth_date is not None:
    		birth_date = user.profile.birth_date

    	
    data = {
        'valid': valid,
        'email': email,
        'contact':contact,
        'address':address,
        'birth_date':birth_date
    }
    
    
    return JsonResponse(data)

myapps/form/templates/form/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
 <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {{ title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/0e07cc82c2.js"></script>

    {% block styles %}
    {% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block scripts %} 
    {% endblock %}
 </head>
  <body>
      {% include 'form/nav.html' %} 
    <div class="jumbotron">
      <div class='container'>
        <div class='row'>
          <div class='col-md-8 col-md-offset-2'>
            
            {% block header %}
            {% endblock %}
            
            {% block legend %}
            {% endblock %}
            
            {% block tab %}
            {% endblock %}
            
            {% block form %}
	          {% endblock %}
	          
	          {% block test %}
	          {% endblock %}
	          
	          {% block end %}
	          {% endblock %}
          </div>
        </div>
      </div>
    </div>
      {% block footer %}
      {% endblock %}
  </body>
</html>
 

myapps/form/templates/form/multiple_form.html
{% load crispy_forms_tags %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<form action="{% url 'form:multiple_form' %}" class='form-horizontal' method='POST'>
{% crispy small_form %}
{% crispy example_form %}
{% crispy button_form %}
</form>

myapps/form/templates/form/nav.html
<div class="container">
<nav class="navbar navbar-inverse bg-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'form:index' %}">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated == False %}
        <li><a href="{% url 'form:login' %}">Sign in</a></li>
        <li><a href="{% url 'form:signup_small' %}">Sign Up</a></li>

         {% else %}
         <li><a href="{% url 'form:logout' %}">Sign Out</a></li>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'form:profile' %}">Profile</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

myapps/form/templates/form/profile.html
{% extends 'form/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'form/base.css' %}" type="text/css" />
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'form/baseScript.js' %}"></script>
{% endblock %}

{% block header %}

{% endblock %}

{% block tab %}

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Account Information</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Personal Information</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">
      <br>
      <form method="post" id='id_user_form' >
      {% csrf_token %}
      {{ user_form|crispy }}
      <button type="submit" class="btn btn-success">Save Changes</button>
      <button type="button" class="btn btn-warning">Cancel</button>
      </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="profile">
      <br>
      <form method="post" id='id_profile_form' >
      {% csrf_token %}
      {{ profile_form|crispy }}
      <button type="submit" class="btn btn-success">Save Changes</button>
      <button type="button" class="btn btn-warning">Cancel</button>
      </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">
      <!--<form method="post" id='id_password_form' >-->
      <!--{% csrf_token %}-->
      <!--{{ user_form|crispy }}-->
      <!--<button type="submit" class="btn btn-success">Save Changes</button>-->
      <!--<button type="button" class="btn btn-warning">Cancel</button>-->
      <!--</form>-->
    </div>
  </div>

</div>

{% endblock %}

myapps/form/templates/form/signin.html
{% extends 'form/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'form/bootstrap-social.css' %}">
{% endblock %}

{% block form %}
  <legend id="legend_id">Login</legend>
    <form id="loginForm" class="form-horizontal" method="post" novalidate="novalidate">
      {% csrf_token %}
        <fieldset> 
          <div id="div_id_username" class="form-group"> 
            <div class="controls col-lg-8 col-md-offset-2"> 
              <input type="text" name="username" maxlength="100" autofocus="" required="" placeholder="Username" class="textinput textInput form-control" id="id_username"> 
            </div> 
          </div> 
  
          <div id="div_id_password" class="form-group"> 
            <div class="controls col-lg-8 col-md-offset-2"> 
              <input type="password" name="password" maxlength="100" required="" placeholder="Password" class="textinput textInput form-control" id="id_password">
            </div> 
          </div> 
        </fieldset>
        <div class="form-group"> 
          <div class="aab controls col-lg-2"></div> 
        <div class="controls col-lg-8 col-md-offset-2"> 
          <input type="submit" name="save" value="Sign In" class="btn btn-primary" id="submit-id-save">
          <input type="button" name="cancel" value="Already have an account?" class="btn" id="button-id-cancel"> </div>
        </div> 
    </form>

 <!-- <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a> -->
<div class="col-md-4 col-md-offset-4">
   
  <a class="btn btn-block btn-social btn-facebook" href="{% url 'social:begin' 'facebook' %}">
    <span class="fa fa-facebook"></span> Sign in with Facebook
  </a>
 
  <a class="btn btn-block btn-social btn-twitter" href="{% url 'social:begin' 'twitter' %}">
    <span class="fa fa-twitter"></span> Sign in with Twitter
  </a>

  <a class="btn btn-block btn-social btn-google" href="{% url 'social:begin' 'google-oauth2' %}">
    <span class="fa fa-google"></span> Sign in with Google
  </a>

</div>
 
<!-- <a href="{% url 'social:begin' 'twitter' %}">Login with Twitter</a><br> -->
<!-- <a href="{% url 'social:begin' 'github' %}">Login with GitHub</a><br>
<br> -->


{% endblock %}

{% block footer %}
  <footer>
    
  </footer>
{% endblock %}

myapps/form/templates/form/signup_small.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SignUp Form </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"  href="{% static 'form/style.css' %}" />
    
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'form/jsForm.js' %}"></script>
 </head>
  <body id='bootstrap-overrides'>

     <div class="jumbotron vertical-center"style="background-color:#298f53">
      <div class='container'>
        <div class='row'>
          <div class='col-md-8 col-md-offset-2'>
            <legend id="legend_id">Register</legend>
            {% crispy form %}
	    
          </div>
        </div>
      </div>
    </div>
  </body>
  

</html>

myapps/form/templates/form/welcome.html
{% extends 'form/base.html' %}
{% load static %}

{# including css #}
{% block styles %}
<link rel="stylesheet" href="{% static 'form/base.css' %}" type="text/css" />
{% endblock %}

{% block test %}
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
    {% else %}
      Welcome! Start your journey!
    {% endif %}
    
{% endblock %}

myapps/form/templates/form/work_space.html
{% extends 'form/base.html' %}
{% load static %}

{# including css #}
{% block styles %}
<link rel="stylesheet" href="{% static 'form/base.css' %}" type="text/css" />
{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'form/work_space.js' %}"></script>
{% endblock %}

{% block test %}
    {% if user.is_authenticated %}
    Hi {{ user.username}}!, your email is {{user.email}}. <br>
    <div id='birthdate'>Your birthdate is: </div>
    {% else %}
      Welcome! Start your journey!
    {% endif %}
{% endblock %}